### ISSUE TITLE
it doesn't generate package.json

### ISSUE THREAD

**Issue by zzsoszz** [gcyStar/generator-webpack-2-es-6#2]
D:\bxdev\github\yeoman-demo2>yo webpack-2-es-6

     _-----_     ╭──────────────────────────╮
    |       |    │  Welcome to the ultimate │
    |--(o)--|    │ generator-webpack-2-es-6 │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Would you like to enable this option? Yes
   create dist\main-build.js
   create src\css\index.css
   create src\img\hw.jpeg
   create src\js\index.js
   create src\vue\helloWorld.vue
   create view\index.html
   create webpack.config.js

D:\bxdev\github\yeoman-demo2>npm run start
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path D:\bxdev\github\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\bxdev\github\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'D:\bxdev\github\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-05-18T04_13_01_485Z-debug.log

D:\bxdev\github\yeoman-demo2>

**Comment by gcyStar** [comment]
@zzsoszz   之前升级导致的问题，已经fix了。
